### PR TITLE
Obvious Fix: fix typo in source directory declaration

### PR DESCRIPTION
**Pull request by bsinou**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bsinou Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-react-and-spring-data-rest&pullRequestId=72)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/tut-react-and-spring-data-rest&pullRequestId=72) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by gregturn** [comment]
I believe the ":" in the middle of your commit breaks this as obvious. If you could just sign the CLA (not that hard) I can merge your change.

**Comment by pivotal-issuemaster** [comment]
@bsinou Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-react-and-spring-data-rest&pullRequestId=72)!

**Comment by bsinou** [comment]
Ok, done. 

By the way, many thanks for this great tutorial!

**Comment by gregturn** [comment]
Thanks @bsinou. Glad you like it!

**Pull request merged**
