### PR TITLE
issue 61 added annotation that links manager to employee after update, also propagated the loggedInManager through the ReactJS classes

### PR DESCRIPTION
**Pull request by jpizagno**
This edit has been confirmed by another user to fix the update. please accept pull request.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jpizagno Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-react-and-spring-data-rest&pullRequestId=68)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/tut-react-and-spring-data-rest&pullRequestId=68) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jpizagno Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-react-and-spring-data-rest&pullRequestId=68)!

**Comment by gregturn** [comment]
I like this pull request @jpizagno. Would you consider squashing this into one commit and rebasing against master?

**Comment by jpizagno** [comment]
OK.  I have squashed into 1 commit which can be seen above.  I think it would be easier to create a new pull request, rather than rebase into master. @gregturn can I just create a new pull request?

**Comment by jpizagno** [comment]
@gregturn   I did not create a new pull request. I did rebase to master, and can see the recent commits from you in my pull-request.  Can you please accept this pull request?  :>

Here is exactly how I rebased 
```
 git clone https://github.com/jpizagno/tut-react-and-spring-data-rest.git
 cd tut-react-and-spring-data-rest
 git remote add spring-guides https://github.com/spring-guides/tut-react-and-spring-data-rest.git
 git fetch spring-guides
 git rebase spring-guides/master
 git config --global push.default simple
 git push -f
```

After doing this, I could see the CI build run again here.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/tut-react-and-spring-data-rest/commit/894a39e961dee95d0a7469d7a7eb87b3f2ae783a.

Thanks @jpizagno !

**Comment by jpizagno** [comment]
@gregturn  I am glad I could help.  Do I get listed as a contributor?

**Comment by gregturn** [comment]
Okay, I used that tip and tweaked the repository. In general, I would not have done that. At least not for a portfolio project. But an isolated tutorial repository was okay.

**Comment by jpizagno** [comment]
Greg.  Thanks.  Again, I am sorry, and will not make that mistake again. If it makes you feel any better, then I am very proud to have contributed to your project.   It made my day!

**Pull request closed without merging**
