### PR TITLE
[Part 5 - Securing the UI and the API] The PUT method will rush the manger…

### PR DESCRIPTION
**Pull request by sunwj326**
The PUT method will rush the manger properites of the employee, that will made the employee lost the manager after updated

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sunwj326 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-react-and-spring-data-rest&pullRequestId=51)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/tut-react-and-spring-data-rest&pullRequestId=51) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sunwj326 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-react-and-spring-data-rest&pullRequestId=51)!

**Comment by jpizagno** [comment]
hello @sunwj326
     I have a pull request opened that may fix this problem.  Can you take a look and comment?

https://github.com/spring-guides/tut-react-and-spring-data-rest/pull/68

thanks

**Comment by gregturn** [comment]
Keep seeing the same messages. Please refresh your fork and work against that.

**Pull request closed without merging**
