### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by jamesyin96**
use quotes in curl command

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jamesyin96 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-react-and-spring-data-rest&pullRequestId=49)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/tut-react-and-spring-data-rest&pullRequestId=49) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jamesyin96 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-react-and-spring-data-rest&pullRequestId=49)!

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/tut-react-and-spring-data-rest/commit/c298ff42f647324da5f461f85da5ad1617fdebd1. Polished and merged to master.

Thanks @jamesyin96!

**Comment by gregturn** [comment]
Resolves #47

**Pull request closed without merging**
